language: bash

matrix:
  include:
    - os: linux
      arch: 
        - amd64
        - arm64
      dist: focal # 20.04
    - os: linux
      dist: bionic # 18.04 (EOL @ April 2023)
    - os: osx
      osx_image: xcode12.5 # 11.3
    - os: osx
      osx_image: xcode12.2 # 10.15.7


install: true
env: REQVER=1.16.7

addons:
  homebrew:
    packages:
    - fish
    update: true
  apt:
    packages:
    - fish
    update: true

script: >-
  bash tests/install.sh &&
  source ~/.bashrc &&
  bash tests/validate.sh &&
  bash tests/remove.sh
  
  bash tests/install-custom-version.sh &&
  source ~/.bashrc &&
  bash tests/custom-version-validate.sh &&
  bash tests/remove.sh

  SHELL=$(which fish) bash tests/install.sh